### ISSUE TITLE
DesktopWindow.getWindowSize() not working on Linux

### ISSUE THREAD

**Issue by Letal1s** [mix1009/desktop_window#14]
Upon trying to retrieve the window size, the error "(MAINWINDOW_NOT_FOUND, GtkWindow not found, null, null)" is thrown.

No matter where I attempt to retrieve the window size, be it on the loading of the app or by the press of a button after the window is already loaded and fully initialised, this error still occurs.

**Comment by JustusFluegel** [comment]
I messed up there, see #9 and #19

**Comment by JustusFluegel** [comment]
@mix1009 can be closed
